services:
  # ======================
  # Backend (Express API)
  # ======================
  - type: web
    name: smartrenter-backend
    env: node
    branch: main
    plan: free
    buildCommand: npm ci
    startCommand: node server.js
    autoDeploy: true
    buildFilter:
      paths:
        ignore:
          - README.md
          - frontend/**
    
  # ======================
  # Frontend (Vite React)
  # ======================
  - type: static
    name: smartrenter-frontend
    branch: main
    buildCommand: npm ci && npm run build
    publishPath: dist
    autoDeploy: true
    buildFilter:
      paths:
        ignore:
          - README.md
          - backend/**
