services:
  - type: web
    name: smartrenter-frontend
    env: node
    branch: main
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    autoDeploy: true
    buildFilter:
      paths:
        ignore:
          - README.md
